name: Release

on:
  push:
    tags:
      - 'v*' # Run workflow on version tags, e.g. v1.0.0.

jobs:
  release:
    permissions:
      id-token: write
      contents: write
      attestations: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          persist-credentials: false

      - uses: grafana/plugin-actions/build-plugin@main
        with:
          # Generate this token as described in:
          # https://grafana.com/developers/plugin-tools/publish-a-plugin/sign-a-plugin
          policy_token: ${{ secrets.GRAFANA_ACCESS_POLICY_TOKEN }}
          # Generate provenance attestation for the release artifacts.
          attestation: true
